### Lista de Todos lo usuarios
GET http://localhost:8080/v1/user
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb3JnZUBnbWFpbC5jb20iLCJhdXRoIjoiVVNFUiIsImV4cCI6MTY5ODYxMzQzMX0.LqxHONbZCZDM1wqacD_RWYM7Ueu808IqMI5tz2vHoRjxSR9FTn87dSxLQ-ItB-T8vRhncKJxiMqidGBJR0GeyA

### Lista de Todos los Empleados
GET http://localhost:8080/v1/user/employees
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb3JnZUBnbWFpbC5jb20iLCJhdXRoIjoiVVNFUiIsImV4cCI6MTY5ODYxMzQzMX0.LqxHONbZCZDM1wqacD_RWYM7Ueu808IqMI5tz2vHoRjxSR9FTn87dSxLQ-ItB-T8vRhncKJxiMqidGBJR0GeyA

### Lista de Todos los Empleados
GET http://localhost:8080/v1/user/customers
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb3JnZUBnbWFpbC5jb20iLCJhdXRoIjoiVVNFUiIsImV4cCI6MTY5ODYxMzQzMX0.LqxHONbZCZDM1wqacD_RWYM7Ueu808IqMI5tz2vHoRjxSR9FTn87dSxLQ-ItB-T8vRhncKJxiMqidGBJR0GeyA

###
GET http://localhost:8080/v1/user/only
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb3JnZUBnbWFpbC5jb20iLCJhdXRoIjoiVVNFUiIsImV4cCI6MTY5ODYxMzQzMX0.LqxHONbZCZDM1wqacD_RWYM7Ueu808IqMI5tz2vHoRjxSR9FTn87dSxLQ-ItB-T8vRhncKJxiMqidGBJR0GeyA

###

GET http://localhost:8080/v1/user/address
Accept: application/json

###

GET http://localhost:8080/v1/user/1
Accept: application/json

###

### Registrar Cliente por MS-USER
PUT http://localhost:8080/v1/user/change/employee
Content-Type: application/json

{
  "id": 2,
  "userName": "JorgeCambio",
  "email": "jorgecambio@gmail.com",
  "authority": {
    "id": "USER"
  },
  "person": {
    "firstName": "jorgeCambio",
    "lastName": "Cambio",
    "documentNumber": "1223829",
    "sex": "hombre",
    "phoneNumber": "77774444",
    "birthdate": "1990-01-03",
    "status": true
  },
  "addressRequests": [
    {
      "description": "Prueba de Guardado"
    }
  ]
}


### Registrar un nuevo USUARIO
POST http://localhost:8080/v1/user/confirm/
Content-Type: application/json

{
  "userName": "maria123",
  "email": "maria123@gmail.com",
  "password": "maria123",
  "person": {
    "firstName": "maria",
    "lastName": "mamani",
    "documentNumber": "23829 lp",
    "sex": "mujer",
    "phoneNumber": "1221323",
    "birthdate": "1992-01-03",
    "status": true
  }
}

### Registrar Cliente por MS-CUSTOMER
POST http://localhost:8080/v1/user/confirm/
Content-Type: application/json

{
  "userName": "erwin",
  "email": "erwin@gmail.com",
  "password": "erwin",
  "rol": "1",
  "person": {
    "firstName": "dsadsdf",
    "lastName": "dsfds",
    "documentNumber": "23829 lp",
    "sex": "hombre",
    "phoneNumber": "2323232",
    "birthdate": "1999-01-03",
    "status": true
  }
}

### Actualizar una IMAGEN NUEVA
PUT http://localhost:8080/v1/user/image/update
Content-Type: application/json

{
  "id": 15,
  "imageUser": "asdgrwghareyjraejn6ya5reth"
}

### Actulizar de un Usuario
PUT http://localhost:8080/v1/user/password/update
Content-Type: application/json

{
  "id": 11,
  "password": "Alejo123",
  "newPassword": "luis123",
  "confirmPassword": "luis123"
}


### Eliminar un cliente
DELETE http://localhost:8080/v1/user/deleted/2
Content-Type: application/json



### Registrar Cliente por MS-USER
PUT http://localhost:8080/v1/user/change/customer
Content-Type: application/json

{
  "id": 2,
  "userName": "JorgeCambio",
  "email": "jorgecambio@gmail.com",
  "authority": {
    "id": "USER"
  },
  "person": {
    "firstName": "jorgeCambio2",
    "lastName": "Cambio2",
    "documentNumber": "1223829",
    "sex": "hombre",
    "phoneNumber": "77774444",
    "birthdate": "1990-01-03",
    "status": true
  },
  "addressRequests": [
    {
      "description": "Prueba de Guardado"
    }
  ]
}
